import os
import subprocess

# Configuration parameters
CRP = '''"%PROGRAMFILES(X86)%\\Google\\Chrome Remote Desktop\\CurrentVersion\\remoting_start_host.exe" --code="4/0AdLIrYdM7xo_gcZ2W1ZJGuoIsl8Y-Nm6DhZvS3UfA0s8KS9gkAIRGtWfvo8Uf8KhagAWuQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=%COMPUTERNAME%'''
Pin = 123456  # Set to your desired PIN (at least 6 digits)
Autostart = True  # Set to True to enable autostart
username = "Ashish"  # Replace with your system username

def installCRD():
    print("Installing Chrome Remote Desktop")
    subprocess.run(['wget', 'https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb'], stdout=subprocess.PIPE)
    subprocess.run(['dpkg', '--install', 'chrome-remote-desktop_current_amd64.deb'], stdout=subprocess.PIPE)
    subprocess.run(['apt', 'install', '--assume-yes', '--fix-broken'], stdout=subprocess.PIPE)

def installDesktopEnvironment():
    print("Installing Desktop Environment")
    os.system("export DEBIAN_FRONTEND=noninteractive")
    os.system("apt install --assume-yes xfce4 desktop-base xfce4-terminal")
    os.system("bash -c 'echo \"exec /etc/X11/Xsession /usr/bin/xfce4-session\" > /etc/chrome-remote-desktop-session'")
    os.system("apt remove --assume-yes gnome-terminal")
    os.system("apt install --assume-yes xscreensaver")
    os.system("systemctl disable lightdm.service")

def installGoogleChrome():
    print("Installing Google Chrome")
    subprocess.run(["wget", "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"], stdout=subprocess.PIPE)
    subprocess.run(["dpkg", "--install", "google-chrome-stable_current_amd64.deb"], stdout=subprocess.PIPE)
    subprocess.run(['apt', 'install', '--assume-yes', '--fix-broken'], stdout=subprocess.PIPE)

def setupAutostart(user):
    os.makedirs(f"/home/{user}/.config/autostart", exist_ok=True)
    link = "https://colab.research.google.com/github/PradyumnaKrishna/Colab-Hacks/blob/master/Colab%20RDP/Colab%20RDP.ipynb"
    colab_autostart = f"""[Desktop Entry]
Type=Application
Name=Colab
Exec=sh -c "sensible-browser {link}"
Icon=
Comment=Open a predefined notebook at session signin.
X-GNOME-Autostart-enabled=true"""
    with open(f"/home/{user}/.config/autostart/colab.desktop", "w") as f:
        f.write(colab_autostart)
    os.system(f"chmod +x /home/{user}/.config/autostart/colab.desktop")
    os.system(f"chown {user}:{user} /home/{user}/.config")

def finishSetup(user, CRP, Pin, Autostart):
    print("Finalizing setup")
    if Autostart:
        setupAutostart(user)
    os.system(f"adduser {user} chrome-remote-desktop")
    command = f"{CRP} --pin={Pin}"
    os.system(f"su - {user} -c '{command}'")
    os.system("service chrome-remote-desktop start")
    print("Setup finished successfully")

try:
    if CRP == "":
        print("Please enter authcode from the given link")
    elif len(str(Pin)) < 6:
        print("Enter a pin more or equal to 6 digits")
    else:
        os.system("apt update")
        installCRD()
        installDesktopEnvironment()
        installGoogleChrome()
        finishSetup(username, CRP, Pin, Autostart)
except NameError as e:
    print("'username' variable not found, please create a user")
